services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    volumes:
      - ./backend:/usr/src/app
    environment:
      - NODE_ENV=production
      - PORT=3000
      - ACCESS_TOKEN_SECRET=jwtaccesssecret
      - REFRESH_TOKEN_SECRET=jwtrefreshsecret
      - MONGODB_URI=mongodb://root:password@mongodb:27017
    ports:
      - "5000:3000"
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - BACKEND_URI=http://localhost:5000/api
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data: